# Generated by Django 4.2.5 on 2023-09-24 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_CustomUser', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='chat_id',
            field=models.IntegerField(default=0),
        ),
    ]
